Write-Host "=== Finance Shorts Factory: Windows setup helper ==="
Write-Host "1) Install Python 3.11+ if missing"
Write-Host "2) Install Ollama from the official Windows installer"
Write-Host "3) Install FFmpeg and ensure ffmpeg.exe / ffprobe.exe are in PATH"
Write-Host "4) Download Piper + one English voice model"
Write-Host "5) Copy config.example.json to config.json and edit the paths"
Write-Host "6) Copy .env.example to .env"
Write-Host "7) Run: py -3 -m venv .venv"
Write-Host "8) Run: .\.venv\Scripts\Activate.ps1"
Write-Host "9) Run: pip install -r requirements.txt"
Write-Host "10) Run: python run_pipeline.py --topic \"What an ETF is in under 60 seconds\""
